"""Initial Migration

Revision ID: 8f7cfec2df0a
Revises: 
Create Date: 2020-12-18 02:30:04.484109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7cfec2df0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('profile_pic_path', sa.String(), nullable=True),
    sa.Column('password_secure', sa.String(length=255), nullable=True),
    sa.Column('pass_secure', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_type', sa.String(length=255), nullable=True),
    sa.Column('start_date_time', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('end_date_time', sa.String(length=255), nullable=True),
    sa.Column('ID_numper', sa.Integer(), nullable=True),
    sa.Column('payment', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_ID_numper'), 'booking', ['ID_numper'], unique=False)
    op.create_index(op.f('ix_booking_car_type'), 'booking', ['car_type'], unique=False)
    op.create_index(op.f('ix_booking_description'), 'booking', ['description'], unique=False)
    op.create_index(op.f('ix_booking_end_date_time'), 'booking', ['end_date_time'], unique=False)
    op.create_index(op.f('ix_booking_mobile'), 'booking', ['mobile'], unique=False)
    op.create_index(op.f('ix_booking_payment'), 'booking', ['payment'], unique=False)
    op.create_index(op.f('ix_booking_start_date_time'), 'booking', ['start_date_time'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('date_posted', sa.DateTime(timezone=250), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_index(op.f('ix_booking_start_date_time'), table_name='booking')
    op.drop_index(op.f('ix_booking_payment'), table_name='booking')
    op.drop_index(op.f('ix_booking_mobile'), table_name='booking')
    op.drop_index(op.f('ix_booking_end_date_time'), table_name='booking')
    op.drop_index(op.f('ix_booking_description'), table_name='booking')
    op.drop_index(op.f('ix_booking_car_type'), table_name='booking')
    op.drop_index(op.f('ix_booking_ID_numper'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
